export const LanguageOption: languageOption[] = [
  { value: 'Python', label: 'Python' },
  { value: 'Javascript', label: 'Javascript' },
  { value: 'HTML', label: 'HTML' },
  { value: 'CSS', label: 'CSS' },
  { value: 'Java', label: 'Java' },
  { value: 'PHP', label: 'PHP' },
  { value: 'Scala', label: 'Scala' },
  { value: 'Perl', label: 'Perl' },
  { value: 'C/C++', label: 'C/C++' },
  { value: 'Kotlin', label: 'Kotlin' },
  { value: 'Swift', label: 'Swift' },
  { value: 'Invision', label: 'Invision' },
  { value: 'InVision Studio', label: 'InVision Studio' },
  { value: 'Kubernetes', label: 'Kubernetes' },
  { value: 'Marvel', label: 'Marvel' },
  { value: 'Microsoft Excel', label: 'Microsoft Excel' },
  { value: 'Microsoft Azure', label: 'Microsoft Azure' },
  { value: 'Miro', label: 'Miro' },
  { value: 'Power BI', label: 'Power BI' },
  { value: 'Proto.io', label: 'Proto.io' },
  { value: 'Qlik', label: 'Qlik' },
  { value: 'Sketch', label: 'Sketch' },
  { value: 'SPSS', label: 'SPSS' },
  { value: 'Tableau', label: 'Tableau' },
  { value: 'Unity 3D', label: 'Unity 3D' },
  { value: 'Unreal Engine', label: 'Unreal Engine' },
  { value: 'Zepelin', label: 'Zepelin' },

];

export const FrameworkOption: frameworkOption[] = [
  { value: 'Oracle', label: 'Oracle' },
  { value: 'Cassandra', label: 'Cassandra' },
  { value: 'SQLite', label: 'SQLite' },
  { value: 'Redis', label: 'Redis' },
  { value: 'MongoDB', label: 'MongoDB' },
  { value: 'MySQL', label: 'MySQL' },
  { value: 'Firebase Realtime Database', label: 'Firebase Realtime Database' },
  { value: 'Microsoft SQL Server', label: 'Microsoft SQL Server' },
  { value: 'JQuery', label: 'JQuery' },
  { value: 'React', label: 'React' },
  { value: 'Spring', label: 'Spring' },
  { value: 'Angular', label: 'Angular' },
  { value: 'Vue.js', label: 'Vue.js' },
  { value: 'Laravel', label: 'Laravel' },
  { value: 'Django', label: 'Django' },
  { value: 'Ruby On Rails', label: 'Ruby On Rails' },
  { value: 'ASP.NET o ASP.NETCore', label: 'ASP.NET o ASP.NETCore' },
  { value: 'Flask', label: 'Flask' },
  { value: 'Express.js', label: 'Express.js' },
  { value: 'FastAPI', label: 'FastAPI' },
  { value: '.NET', label: '.NET' },
  { value: 'Node.js', label: 'Node.js' },

];

export const ToolOption: toolOption[] = [
  { value: 'Github', label: 'Github' },
  { value: 'Adobe Illustrator', label: 'Adobe Illustrator' },
  { value: 'Adobe Photoshop', label: 'Adobe Photoshop' },
  { value: 'Adobe XD', label: 'Adobe XD' },
  { value: 'AWS', label: 'AWS' },
  { value: 'Docker', label: 'Docker' },
  { value: 'Figma', label: 'Figma' },
  { value: 'GIT', label: 'GIT' },
  { value: 'Google Analytics', label: 'Google Analytics' },
  { value: 'Google Cloud Plataform', label: 'Google Cloud Plataform' },
  { value: 'Google Data Studio', label: 'Google Data Studio' },
  { value: 'Invision', label: 'Invision' },
  { value: 'TypeScript', label: 'TypeScript' },
  { value: 'Assembly', label: 'Assembly' },
  { value: 'R', label: 'R' },
  { value: 'Go', label: 'Go' },
  { value: 'Bash/Shell', label: 'Bash/Shell' },

];